name: PerPlayerHorse
version: ${project.version}
main: koral.horseplugin.HorsePlugin
api-version: 1.13
authors: [koral]
description: Plugin for perplayer horses
commands:
  wierzchowiec:
  wierzchowiecvip:
  wierzchowiecmvip:
  kon1:
  kon2:
  kon3: